### ISSUE TITLE
latex or html?

### ISSUE THREAD

**Issue by jamesalbert** [ArturGrigio/statistics-distributions-functions#3]
I'm in favor for html cause the grid system is better for pushing things really closely together.

**Comment by hfloresr** [comment]
I just converted it into table format... check it out. The math formatting
on html seemed a bit harsh for my taste.

I'm open to suggestions.

**Comment by ArturGrigio** [comment]
I like latex more, HTML is too messy, Latex looks cleaner.
Lets move forward with Latex

**Comment by ArturGrigio** [comment]
Can you add images to latex?

I am intending to add the solutions of "STATS67-MIDTERMEXAM-2" as images to the end of the Cheat Sheet.

**Comment by jamesalbert** [comment]
yeah but how small are you going to have to make those images and at that point will they even be legible? We should totally stick with one type of file though so we get the most work output possible instead of some of us working on html and others working on latex?

**Comment by jamesalbert** [comment]
I'm down for either or though ;)

**Comment by hfloresr** [comment]
It's probably better if we put key steps in solving solutions. Putting pics
of whole solutions can be very cluttering, and you don't want to try to
figure things out during a time exam. I'll continue with LaTeX since it's
more pleasant for me to read, if you guys want html just take what's useful
and convert it.

I'm down for either or though ;)

**Comment by jamesalbert** [comment]
Sounds good, and who knows, we might even me able to merge the two towards the end
