### ISSUE TITLE
How can we incorporate the solutions into the cheat sheet?

### ISSUE THREAD

**Issue by ArturGrigio** [ArturGrigio/statistics-distributions-functions#5]
I layed out all the practice solutions side by side (2x4, 3x4, and 2x4) but it's too much, it won't be visible if printed. 

Is there a better way to doing this?

**Comment by hfloresr** [comment]
You're gonna kill yourself reading those solutions. I suggest stripping it down so it's streamlined and you know how and why without all the little details.

**Comment by jamesalbert** [comment]
Idk about you guys, but we should add solutions, if at all, towards the end. the material doesn't seem that hard and I feel that the initial setup of the problem is where it's most tough. let's make sure we add as much stats / calculus formulas as possible before we put it full solutions. Or maybe even add only the solutions to the really hard questions like linear regression for example.

**Comment by jamesalbert** [comment]
I also wanted to get your guys' take on whether or not to add full Std normal dist / T tables or just the most widely used values (ie alpha = .05, etc)

**Comment by ArturGrigio** [comment]
Incorporating the homework into the cheat sheet wasn't a good idea. I removed all the HW images
